sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  # - docker run -e CI=true docker-react
  - docker run -e CI=true docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "react-env"
  bucket_name: "elasticbeanstalk-us-east-1-060542311733"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  serect_access_key: $AWS_SERECT_KEY
